2.1 Assignment 1

In [2]:
import torch

# Create a 2D random tensor
x1 = torch.rand((5, 6))

#the shape, data type, and mean of all elements
x1_shape = x1.shape
x1_dtype = x1.dtype
x1_mean = x1.mean().item()

print(f"Shape of x1: {x1_shape}")
print(f"Data type of x1: {x1_dtype}")
print(f"Mean of all elements in x1: {x1_mean}")


Shape of x1: torch.Size([5, 6])
Data type of x1: torch.float32
Mean of all elements in x1: 0.5126557946205139


2.2 Assignment 2

In [3]:
import torch
x2 = torch.randint(0, 10, (4, 4))

x2_float = x2.float()
difference = x2_float - x2
print("x2 (Integer Tensor):")
print(x2)
print("\nx2_float (Converted to Float):")
print(x2_float)
print("\nDifference (x2_float - x2):")
print(difference)


x2 (Integer Tensor):
tensor([[2, 3, 4, 7],
        [6, 4, 4, 6],
        [6, 6, 7, 6],
        [0, 6, 7, 6]])

x2_float (Converted to Float):
tensor([[2., 3., 4., 7.],
        [6., 4., 4., 6.],
        [6., 6., 7., 6.],
        [0., 6., 7., 6.]])

Difference (x2_float - x2):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


The difference will be zero for all elements because the conversion of x2 from integer to float does not alter the underlying values, only their data type. The original values remain unchanged, and the subtraction results in zero.

2.3

In [4]:
import torch
x3 = torch.rand((3, 2))
x3_transposed = x3.T
result = x3 @ x3_transposed
print("Shape of the result:", result.shape)


Shape of the result: torch.Size([3, 3])


2.4


In [5]:
import torch

# Create two tensors x4_A and x4_B of shape (2, 3) with random integers in range [1, 5]
x4_A = torch.randint(1, 6, (2, 3))
x4_B = torch.randint(1, 6, (2, 3))

# Element-wise addition
addition_result = x4_A + x4_B

# Element-wise subtraction
subtraction_result = x4_A - x4_B

# Element-wise multiplication
multiplication_result = x4_A * x4_B

# Print each result and their shapes
print("x4_A:")
print(x4_A)
print("\nx4_B:")
print(x4_B)
print("\nAddition Result:")
print(addition_result)
print("Shape:", addition_result.shape)
print("\nSubtraction Result:")
print(subtraction_result)
print("Shape:", subtraction_result.shape)
print("\nMultiplication Result:")
print(multiplication_result)
print("Shape:", multiplication_result.shape)


x4_A:
tensor([[5, 1, 4],
        [4, 5, 2]])

x4_B:
tensor([[5, 1, 1],
        [5, 1, 5]])

Addition Result:
tensor([[10,  2,  5],
        [ 9,  6,  7]])
Shape: torch.Size([2, 3])

Subtraction Result:
tensor([[ 0,  0,  3],
        [-1,  4, -3]])
Shape: torch.Size([2, 3])

Multiplication Result:
tensor([[25,  1,  4],
        [20,  5, 10]])
Shape: torch.Size([2, 3])


2.5

In [6]:
import torch
x5 = torch.linspace(1, 12, steps=12).reshape(3, 4)
x5_flattened = x5.flatten()

print("Original shape of x5:", x5.shape)
print("Flattened shape of x5:", x5_flattened.shape)


Original shape of x5: torch.Size([3, 4])
Flattened shape of x5: torch.Size([12])


2.6

In [7]:
import torch

x6 = torch.rand((4, 4))
column_wise_sum = x6.sum(dim=0)
row_wise_sum = x6.sum(dim=1)

print("Tensor x6:")
print(x6)
print("\nColumn-wise sum:")
print(column_wise_sum)
print("Shape:", column_wise_sum.shape)
print("\nRow-wise sum:")
print(row_wise_sum)
print("Shape:", row_wise_sum.shape)


Tensor x6:
tensor([[0.7344, 0.4615, 0.9654, 0.9123],
        [0.9853, 0.9805, 0.1840, 0.1345],
        [0.6452, 0.3007, 0.5669, 0.8034],
        [0.5431, 0.7487, 0.0443, 0.6346]])

Column-wise sum:
tensor([2.9080, 2.4915, 1.7606, 2.4848])
Shape: torch.Size([4])

Row-wise sum:
tensor([3.0736, 2.2843, 2.3162, 1.9707])
Shape: torch.Size([4])


2.7

In [8]:
import torch
x7_A = torch.rand((2, 2))
x7_B = torch.rand((2, 2))

concat_dim0 = torch.cat((x7_A, x7_B), dim=0)
concat_dim1 = torch.cat((x7_A, x7_B), dim=1)

print("Tensor x7_A:")
print(x7_A)
print("\nTensor x7_B:")
print(x7_B)
print("\nConcatenated along dimension 0 (Shape (4, 2)):")
print(concat_dim0)
print("\nConcatenated along dimension 1 (Shape (2, 4)):")
print(concat_dim1)


Tensor x7_A:
tensor([[0.1316, 0.1887],
        [0.5007, 0.9808]])

Tensor x7_B:
tensor([[0.7943, 0.9680],
        [0.7933, 0.1641]])

Concatenated along dimension 0 (Shape (4, 2)):
tensor([[0.1316, 0.1887],
        [0.5007, 0.9808],
        [0.7943, 0.9680],
        [0.7933, 0.1641]])

Concatenated along dimension 1 (Shape (2, 4)):
tensor([[0.1316, 0.1887, 0.7943, 0.9680],
        [0.5007, 0.9808, 0.7933, 0.1641]])


2.8

In [10]:
import torch
x8 = torch.randint(0, 10, (2, 3, 4))
x8 = x8.float()
max_value = x8.max()
mean_dim2 = x8.mean(dim=2)

print("Tensor x8:")
print(x8)
print("\nMaximum value in x8:", max_value)
print("\nMean along dimension 2:")
print(mean_dim2)
print("Shape of mean along dimension 2:", mean_dim2.shape)


Tensor x8:
tensor([[[0., 8., 6., 5.],
         [0., 7., 4., 4.],
         [3., 0., 5., 9.]],

        [[1., 9., 0., 1.],
         [6., 0., 8., 0.],
         [1., 2., 8., 9.]]])

Maximum value in x8: tensor(9.)

Mean along dimension 2:
tensor([[4.7500, 3.7500, 4.2500],
        [2.7500, 3.5000, 5.0000]])
Shape of mean along dimension 2: torch.Size([2, 3])


2.9

In [11]:
import torch

x9 = torch.rand((3, 3))
determinant = torch.linalg.det(x9)

print("Matrix x9:")
print(x9)
print("\nDeterminant of x9:", determinant.item())


Matrix x9:
tensor([[0.9293, 0.3403, 0.4535],
        [0.6525, 0.0027, 0.9569],
        [0.4956, 0.0559, 0.0978]])

Determinant of x9: 0.10614281892776489


The matrix is nearly singular.

2.10

In [12]:
import torch

x10 = torch.randn((3, 2))
x10_stacked = torch.stack([x10] * 3, dim=1)


print("Shape of x10_stacked:", x10_stacked.shape)


Shape of x10_stacked: torch.Size([3, 3, 2])
